name: augen
description: A Flutter plugin for building AR applications using ARCore on Android and RealityKit on iOS. Enables pure Dart AR development without native code.
version: 0.4.0
homepage: https://github.com/AminMemariani/augen
repository: https://github.com/AminMemariani/augen
issue_tracker: https://github.com/AminMemariani/augen/issues

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.augen
        pluginClass: AugenPlugin
      ios:
        pluginClass: AugenPlugin
